require "bundler/gem_tasks"
require "rake/testtask"
require "./lib/find_pi"

Rake::TestTask.new do |t|
  t.libs << 'test'
  t.test_files = FileList['test/test*.rb']
  t.verbose = true
end

task :default do
  FindPi.prompt_user
end

#desc "Run tests"
#task :default => :test
